### ISSUE TITLE
json

### ISSUE THREAD

**Issue by LuckyLyz** [yunqiang-sun/get_LibSeat#2]
大佬有详细的使用方法吗？看不懂如何使用

**Comment by LuckyLyz** [comment]
> 大佬有详细的使用方法吗？看不懂如何使用

还有如何弄json配置，如何放到本地web服务器上

**Comment by yunqiang-sun** [comment]
不是大佬 这就是一个简易的自动发包脚本 主要是源于这个预约系统的客户端和服务器端间的通信用的都是明文的方式所以可以很容易地抓包看到数据格式   json文件我没有放上来  格式如下:

`{
    "length":2,
    "data":[
            {"info":"张三同学 6F 第五阅览室南区 200号","studentNum":"XXXXXXXXX","password":"XXXXXX","seatId":"XXXXXX","startTime":540,"endTime":1320},
 {"info":"李四同学 6F 第五阅览室南区 201号","studentNum":"XXXXXXXXX","password":"XXXXXX","seatId":"XXXXXX","startTime":540,"endTime":1320}
   ]
}`

length字段为json中存放的账号的个数 在上面这个例子中是两个账号 info是记录该账号的信息(这个字段是方便自己看的，程序不读取所以不加也不影响运行) studentNum是学号字段 password是密码字段 seatId是座位数据库id字段 startTime是开始时间 这个数值是从0.00开始的分钟数 比如开始时间是8:00 那这个字段的值就是 8*60=480 endTime是结束时间字段 与开始时间单位相同

把这个json放到本地web服务器中即可 其实最直接的是直接用读文件的方法读json 但是我实际测试的时候发现好像有点问题 不太清楚为啥 所以采用了http方法读json

**Comment by yunqiang-sun** [comment]
> > 大佬有详细的使用方法吗？看不懂如何使用
> 
> 还有如何弄json配置，如何放到本地web服务器上


不是大佬 这就是一个简易的自动发包脚本 主要是源于这个预约系统的客户端和服务器端间的通信用的都是明文的方式所以可以很容易地抓包看到数据格式 json文件我没有放上来 格式如下:

`{ 
        "length":2,
         "data":[ 
                    {"info":"张三同学 6F 第五阅览室南区 200号","studentNum":"XXXXXXXXX","password":"XXXXXX","seatId":"XXXXXX","startTime":540,"endTime":1320},
                  {"info":"李四同学 6F 第五阅览室南区 201号","studentNum":"XXXXXXXXX","password":"XXXXXX","seatId":"XXXXXX","startTime":540,"endTime":1320}
              ]
 }`


length字段为json中存放的账号的个数 在上面这个例子中是两个账号 info是记录该账号的信息(这个字段是方便自己看的，程序不读取所以不加也不影响运行) studentNum是学号字段 password是密码字段 seatId是座位数据库id字段 startTime是开始时间 这个数值是从0.00开始的分钟数 比如开始时间是8:00 那这个字段的值就是 8*60=480 endTime是结束时间字段 与开始时间单位相同把这个json放到本地web服务器中即可 其实最直接的是直接用读文件的方法读json 但是我实际测试的时候发现好像有点问题 不太清楚为啥 所以采用了http方法读json
